version: '3.8'

services:
  postgres:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - just-cars-network

  api:
    build: .
    container_name: api
    restart: unless-stopped
    links:
      - postgres
    depends_on:
      - postgres
    tty: true
    ports:
      - 3001:3000
    networks:
      - just-cars-network

volumes:
  postgres:

networks:
  just-cars-network:
    driver: bridge
