default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  username: postgres
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: just_cars_development

test:
  <<: *default
  database: just_cars_test
